# Generated by Django 4.0.10 on 2023-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ManyToManyField(blank=True, to='projects.category'),
        ),
    ]
