# Generated by Django 4.0.10 on 2023-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='tech',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
