# Generated by Django 4.0.10 on 2023-12-02 07:03

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to=info.models.get_avatar_file_path)),
                ('profession', models.CharField(max_length=255)),
                ('youtube', models.URLField(max_length=375)),
                ('github', models.URLField(max_length=375)),
                ('linkedin', models.URLField(max_length=375)),
                ('telegram', models.URLField(max_length=375)),
                ('description', models.TextField()),
            ],
        ),
    ]
