# Generated by Django 4.0.10 on 2023-12-02 12:55

from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField()),
                ('cv', models.FileField(upload_to=info.models.get_cv_file_path)),
            ],
        ),
    ]
